# -*- encoding: utf-8 -*-

=begin
#The One Api Client

#This is a sample client for the the-one-api service. This client implements endpoints related to movie and quotes.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "reed_sdk/version"

Gem::Specification.new do |s|
  s.name        = "reed_sdk"
  s.version     = ReedSdk::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Reed"]
  s.email       = [""]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "The One Api Client Ruby Gem"
  s.description = "This is a sample client for the the-one-api service. This client implements endpoints related to movie and quotes."
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
