=begin
#The One Api Client

#This is a sample client for the the-one-api service. This client implements endpoints related to movie and quotes.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::TheOneApiApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TheOneApiApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::TheOneApiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TheOneApiApi' do
    it 'should create an instance of TheOneApiApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::TheOneApiApi)
    end
  end

  # unit tests for retrieve_movie
  # Retrieve a movie by a specific ID
  # Retrieves a specific movie by ID or returns an empty response.
  # @param id Movie ID
  # @param [Hash] opts the optional parameters
  # @return [Movie]
  describe 'retrieve_movie test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_movie_quotes
  # Retrieve a specific movies quotes.
  # Retrieve a sepcific movie&#39;s quotes or return an empty response.
  # @param id Movie ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [Integer] :page 
  # @option opts [Integer] :offset 
  # @option opts [String] :sort 
  # @return [Quotes]
  describe 'retrieve_movie_quotes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_movies
  # Retrieve all movies
  # Retrieves all movies in the database.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [Integer] :page 
  # @option opts [Integer] :offset 
  # @option opts [String] :sort 
  # @return [Movies]
  describe 'retrieve_movies test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_quote
  # Retrieve a specific movie quote
  # Retrieves a specific quote by ID or returns an empty response.
  # @param id Quote ID
  # @param [Hash] opts the optional parameters
  # @return [Quote]
  describe 'retrieve_quote test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_quotes
  # Retrieve all movie quotes
  # Retrieves a list of all movie quotes
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [Integer] :page 
  # @option opts [Integer] :offset 
  # @option opts [String] :sort 
  # @return [Quotes]
  describe 'retrieve_quotes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
