=begin
#The One Api Client

#This is a sample client for the the-one-api service. This client implements endpoints related to movie and quotes.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::QuotesAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::QuotesAllOf do
  let(:instance) { OpenapiClient::QuotesAllOf.new }

  describe 'test an instance of QuotesAllOf' do
    it 'should create an instance of QuotesAllOf' do
      expect(instance).to be_instance_of(OpenapiClient::QuotesAllOf)
    end
  end
  describe 'test attribute "docs"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
